spring.application.name=server
server.port=8081
# MySQL Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
jwt.secret=${JWT_SECRET:ThisIsASecretKeyForJwtAuthenticationWhichMustBeAtLeast256BitsLong123!}
jwt.expiration=${JWT_EXPIRATION:86400000}

jasypt.encryptor.password=${JASYPT_PASSWORD:HospitalSecretKey123!}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dummy@gmail.com
spring.mail.password=dummy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
